title: "Sonja Savolainen"
author: "Sonja Savolainen"
description: "University of Helsinki"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md", title: "Home"}
  - {file: "research.md", title: "Research"}
  - {file: "contact.md", title: "Contact"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: at, url: "mailto:sonja.savolainen@helsinki.fi"}
  - {title: Github, icon: github, url: "https://github.com/sonjasav"}
  - {title: Twitter, icon: twitter, url: "https://twitter.com/SonjaSavolainen"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-seo-tag
